CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY,
    user_name VARCHAR,
    avatar_path VARCHAR,
    phone VARCHAR,
    email VARCHAR,
    evaluate TEXT,
    coin INTEGER NOT NULL DEFAULT 0,
    password VARCHAR NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "admin" (
    id UUID PRIMARY KEY,
    user_name VARCHAR,
    avatar_path VARCHAR,
    phone VARCHAR,
    email VARCHAR,
    password VARCHAR NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "item" (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    image_path VARCHAR NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id UUID REFERENCES "user"(id)
);

CREATE TABLE IF NOT EXISTS auction (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    condition_evaluate INTEGER,
    status VARCHAR NOT NULL,
    time_auction TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT,
    time_register TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auction_item (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_sell UUID REFERENCES "user"(id),
    auction_id UUID REFERENCES auction(id),
    auction_user_id UUID REFERENCES auction_user(id),
    item_id UUID REFERENCES item(id)
);

CREATE TABLE IF NOT EXISTS report (
    id UUID PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator_id UUID REFERENCES "user"(id),
    evaluatee_id UUID REFERENCES "user"(id)
);

CREATE TABLE IF NOT EXISTS history (
    id UUID PRIMARY KEY,
    description TEXT,
    amount INTEGER NOT NULL DEFAULT 0,
    kind INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id UUID REFERENCES "user"(id),
    auction_item_id UUID REFERENCES auction_item(id)
);

CREATE TABLE IF NOT EXISTS inspection (
    id UUID PRIMARY KEY,
    description_admin TEXT NOT NULL,
    coin INTEGER NOT NULL DEFAULT 0,
    kind VARCHAR NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    item_id UUID REFERENCES item(id),
    admin_id UUID REFERENCES admin(id)
);

CREATE TABLE IF NOT EXISTS love_item (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id UUID REFERENCES "user"(id),
    item_id UUID REFERENCES item(id)
);

CREATE TABLE IF NOT EXISTS auction_user (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id UUID REFERENCES "user"(id),
    auction_id UUID REFERENCES auction(id)
);

CREATE TABLE IF NOT EXISTS "message" (
    id UUID PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id UUID REFERENCES "user"(id),
    auction_user_id UUID REFERENCES auction_user(id)
);
